name: mapbox_turn_by_turn
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_mapbox_navigation: ^0.1.8
  shared_preferences: ^2.0.13
  flutter_native_splash: ^2.2.16
  location: ^5.0.0
  google_fonts: ^5.1.0
  flutter_dotenv: ^5.0.2
  dio: ^5.2.1+1
  mapbox_gl: ^0.16.0
  intl: ^0.18.1
  flutter_rating_bar: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash:

flutter_native_splash:
  color: "#3F51B5"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/image/
    - assets/config/
